### ISSUE TITLE
Transfer repo to Bioconductor org

### ISSUE THREAD

**Issue by lgatto** [Bioconductor/EuroBioc2017#1]
@mtmorgan - I believe you would prefer this repo to be within the Bioconductor org, but I lack rights to transfer it myself.

**Comment by mtmorgan** [comment]
I elevated your permissions, can you try again?

**Comment by lgatto** [comment]
I still get 
> You don’t have the permission to create repositories on Bioconductor

**Comment by lgatto** [comment]
Just tried again after getting the email from Github, and it seemed to work, but now it doesn't again.

**Comment by lgatto** [comment]
Also, will you want a dedicated admin group for that repo?

**Comment by mtmorgan** [comment]
Can you try again?

**Comment by lgatto** [comment]
Worked, thanks! 

Could you create a team with admin rights and add @lgatto, @markdunning and @LTLA.

**Comment by mtmorgan** [comment]
team created

**Comment by lgatto** [comment]
It looks like there is a delay from when I try something and permissions are actually enabled, as I now have admin rights to this repo and should be able to sort things out.
